### ISSUE TITLE
Looking for annotations from human evaluation

### ISSUE THREAD

**Issue by jigsaw2212** [cylnlp/dialogsum#12]
Hi, The paper states that you have Fluency, Consistency, Relevance and Coherence scores by a judge for 50 dialogues in the test set. Can you share those? Would be super helpful. Thanks!

**Comment by cylnlp** [comment]
Hi Divyansh,

I am sorry that I did not keep those data.

Yulong

Divyansh Agarwal ***@***.***> 于2023年2月21日周二 05:08写道：
