### ISSUE TITLE
Regarding license

### ISSUE THREAD

**Issue by ranxue** [cylnlp/dialogsum#16]
Hi,

DailyDialog is mentioned as a data source for DialogSum. Based on http://yanran.li/dailydialog, DailyDialog is [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). And author indicated that: 
```If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original. Any third party annotation is welcome. Note the dataset may not be adopted for commercial use.```

Does this mean DialogSum should also be under CC BY-NC-SA license? Or am I missing anything?

Thanks!

**Comment by cylnlp** [comment]
@ranxue Thanks for bring up this issue. I have changed the license to [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
