### ISSUE TITLE
关于topic的疑问

### ISSUE THREAD

**Issue by yuhangT** [cylnlp/DialogSum#3]
您好，请问，论文中写到把数据topic聚类成20类，但为何数据中标注的topic远远超过20？

**Comment by cylnlp** [comment]
您好。

论文中呈现的是使用k-means算法对主题进行聚类的结果。我们比较了k = 10， 20， 30，发现k = 20时，聚类效果比较好。但这不代表对话的主题只有20个。

祝好

**Comment by yuhangT** [comment]
> 您好。
> 
> 论文中呈现的是使用k-means算法对主题进行聚类的结果。我们比较了k = 10， 20， 30，发现k = 20时，聚类效果比较好。但这不代表对话的主题只有20个。
> 
> 祝好

您好。
非常感谢您的回复，请问可以分享下你们的最优的聚类结果吗？如果可以的话，个人邮箱是：3220190872@bit.edu.cn，期待您的回复！
