### ISSUE TITLE
Leaderboard Model

### ISSUE THREAD

**Issue by Amoy-Ou** [cylnlp/dialogsum#7]
Hello,
It's an interesting task, could you share the paper or code of the model in the Leaderboard.

**Comment by cylnlp** [comment]
Hi, @Amoy-Ou thank you for your interest.
Usage of the BART baseline has just been uploaded by @chenllliang.
You may now find it in the baseline file, including model training and evaluation.

**Comment by cylnlp** [comment]
@Amoy-Ou sorry I misunderstood your question.

The shared task is now open for calling participants, and the leaderboard shows the results of submitted ones, which are not built by us.

**Comment by Amoy-Ou** [comment]
Thanks for your reply!
